# Generated by Django 2.2 on 2019-04-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0003_auto_20190419_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='start',
        ),
        migrations.AddField(
            model_name='card',
            name='is_joker',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='is_joker_call',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='is_mighty',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='turn',
            name='number',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='int_value',
            field=models.IntegerField(choices=[(14, 14), (13, 13), (12, 12), (11, 11), (10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (16, 16), (15, 15), (1, 1)], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.IntegerField(choices=[('spade', 'spade'), ('diamond', 'diamond'), ('clover', 'clover'), ('heart', 'heart'), ('Joker', 'Joker')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='value',
            field=models.CharField(choices=[('A', 'A'), ('K', 'K'), ('Q', 'Q'), ('J', 'J'), ('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('Mighty', 'Mighty'), ('Joker', 'Joker')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='first',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='number',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(db_index=True, default='bot', max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='turn',
            name='position',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], db_index=True, default=0),
        ),
    ]
