# Generated by Django 2.2 on 2019-04-21 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mighty', '0005_auto_20190421_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_kiruda',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='in_election', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('status', model_utils.fields.StatusField(choices=[('pass', 'pass'), ('declaration', 'declaration')], default='pass', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('suit', models.CharField(choices=[('nokiru', 'nokiru'), ('spade', 'spade'), ('diamond', 'diamond'), ('clover', 'clover'), ('heart', 'heart')], db_index=True, max_length=10)),
                ('value', models.IntegerField(choices=[(12, 12), (20, 20), (19, 19), (18, 18), (17, 17), (16, 16), (15, 15), (14, 14), (13, 13)], db_index=True, default=13)),
                ('is_successful', models.BooleanField(db_index=True, default=False)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mighty.Game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mighty.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
